# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Hugo Blox Builder.'
    twitter: 'amar36'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true


############################
## Contact Widget setup   ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email : "amarmandavia@gmail.com"
address : "VA Boston Healthcare System<br>150 S Huntington St.<br>Boston, MA 02130"

# Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
office_hours : ""

# Enter an optional link for booking appointments (e.g. calendly.com).
#appointment_url : "https://calendly.com"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links : [
  # {icon : "twitter", icon_pack : "fab", name : "DM Me", link : "https://twitter.com/Twitter"},
  # {icon : "skype", icon_pack : "fab", name : "Skype Me", link : "skype:echo123?call"},
  # {icon : "keybase", icon_pack : "fab", name : "Chat on Keybase", link : "https://keybase.io/"},
  # {icon : "comments", icon_pack : "fas", name : "Discuss on Forum", link : "https://discourse.gohugo.io"},
  # {icon : "telegram", icon_pack : "fab", name : "Telegram Me", link : "https://telegram.me/@Telegram"},
  ]

# Display a map.
# To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
# a map provider below.
# To use Google Maps, set `map : 1` and enter your API key that can be obtained here:
#   https://developers.google.com/maps/documentation/javascript/get-api-key
# To use OpenStreetMap tiles, set `map : 2`.
# To use OpenStreetMap on a high traffic site, set `map : 3` and enter your API key that can be obtained here:
#   https://www.mapbox.com/studio/account/tokens
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
#
# Map provider:
#   0: No map
#   1: Google Maps
#   2: OpenStreetMap (Mapnik)
#   3: OpenStreetMap (Mapbox)
map : 0
map_api_key : ""
latitude : "37.4275"
longitude : "-122.1697"
zoom : 15

############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css : ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js : ["custom"]`.
plugins_css : []
plugins_js  : []

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar : false

# Align the main menu to the right of the page? (true/false)
menu_align_right : false

# Show estimated reading time for posts? (true/false)
reading_time : true

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count : true

# Display next/previous section pager? (true/false)
section_pager : false
docs_section_pager : true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing : true

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine : 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id : ""
    api_key : ""
    index_name : ""
    show_logo : false
